name: Go Nancy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Nancy
      uses: whyjustin/nancy-github-action@master
      with:
        target: go.sum